#!/usr/bin/env python3
"""Regenerate docs/index.html from scan reports found in docs/.

Usage: python3 generate-docs-index.py docs/
"""

import html
import re
import sys
from pathlib import Path


def extract_stats(html_file):
    content = html_file.read_text()

    def first(pattern):
        m = re.search(pattern, content, re.DOTALL)
        return m.group(1) if m else None

    return {
        "date": first(r"Scanned (\d{4}-\d{2}-\d{2})") or "",
        "ops": first(r'card-value">(\d+/\d+)</div><div class="card-label">Operators Affected') or "?",
        "total": first(r'card-value">(\d+)</div><div class="card-label">Total Findings') or "0",
        "critical": first(r"card critical.*?card-value\">(\d+)") or "0",
        "high": first(r"card high.*?card-value\">(\d+)") or "0",
        "medium": first(r"card medium.*?card-value\">(\d+)") or "0",
        "low": first(r"card low.*?card-value\">(\d+)") or "0",
    }


def version_sort_key(version):
    parts = re.split(r"[-.]", version)
    result = []
    for p in parts:
        try:
            result.append((0, int(p)))
        except ValueError:
            result.append((1, p))
    return result


def main():
    docs_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("docs")

    scans = []
    for scan_dir in sorted(docs_dir.glob("ocp-operator-scan-*")):
        html_files = list(scan_dir.glob("release-scan-*.html"))
        if not html_files:
            continue
        version = scan_dir.name.replace("ocp-operator-scan-", "")
        stats = extract_stats(html_files[0])
        rel_dir = scan_dir.name
        rel_html = f"{rel_dir}/{html_files[0].name}"
        scans.append({"version": version, "rel_html": rel_html, **stats})

    scans.sort(key=lambda s: version_sort_key(s["version"]), reverse=True)

    rows = ""
    for s in scans:
        v = html.escape(s["version"])
        rows += f"""    <tr>
      <td><a class="version" href="{html.escape(s['rel_html'])}">OCP {v}</a></td>
      <td class="ops">{html.escape(s['ops'])} affected</td>
      <td><span class="badge c">{html.escape(s['critical'])}</span></td>
      <td><span class="badge h">{html.escape(s['high'])}</span></td>
      <td><span class="badge m">{html.escape(s['medium'])}</span></td>
      <td><span class="badge l">{html.escape(s['low'])}</span></td>
      <td class="total">{html.escape(s['total'])}</td>
      <td class="date">{html.escape(s['date'])}</td>
    </tr>
"""

    index = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Operator Anti-Pattern Reports</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 60px auto; padding: 0 24px; color: #151515; }}
h1 {{ font-size: 1.5rem; margin-bottom: 8px; }}
p {{ color: #6a6e73; margin-bottom: 24px; }}
a {{ color: #0066cc; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
table {{ width: 100%; border-collapse: separate; border-spacing: 0; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 24px; }}
th {{ background: #f0f0f0; padding: 10px 14px; text-align: left; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; color: #6a6e73; border-bottom: 2px solid #d2d2d2; }}
td {{ padding: 12px 14px; border-bottom: 1px solid #eee; background: white; }}
tr:last-child td {{ border-bottom: none; }}
tr:hover td {{ background: #f0f4ff; }}
.version {{ font-weight: 600; font-size: 1.05rem; }}
.badge {{ display: inline-block; min-width: 26px; padding: 2px 7px; border-radius: 10px; font-size: 0.75rem; font-weight: 700; text-align: center; }}
.c {{ background: #fce4e4; color: #c9190b; }}
.h {{ background: #fef3e0; color: #ec7a08; }}
.m {{ background: #fef9e5; color: #f0ab00; }}
.l {{ background: #e8f5e3; color: #3e8635; }}
.total {{ font-weight: 700; }}
.date {{ font-size: 0.8rem; color: #6a6e73; }}
.ops {{ font-size: 0.85rem; color: #6a6e73; }}
footer {{ text-align: center; padding: 16px 0; font-size: 0.8rem; color: #6a6e73; }}
</style>
</head>
<body>
<h1>OCP Operator Anti-Pattern Reports</h1>
<p>Automated scans of OpenShift release operators for
  <a href="https://developers.redhat.com/articles/2026/07/06/5-anti-patterns-cause-kubernetes-operator-vulnerabilities">controller-runtime cache anti-patterns</a> and
  <a href="https://developers.redhat.com/articles/2026/06/01/protect-your-kubernetes-operator-oomkill">OOMKill vulnerabilities</a>.
</p>
<table>
  <thead>
    <tr>
      <th>Release</th>
      <th>Operators</th>
      <th>C</th>
      <th>H</th>
      <th>M</th>
      <th>L</th>
      <th>Total</th>
      <th>Scanned</th>
    </tr>
  </thead>
  <tbody>
{rows}  </tbody>
</table>
<footer>
  Generated by <a href="https://github.com/eformat/operator-anti-patterns">operator-anti-patterns</a>
</footer>
</body>
</html>
"""

    output = docs_dir / "index.html"
    output.write_text(index)
    print(f"Updated {output} with {len(scans)} reports")


if __name__ == "__main__":
    main()
